spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: PHNBK_LOCAL
    password: abc_123
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
server:
  port: 8099
  servlet:
    context-path: /SSA
    
